// Code generated by protoc-gen-go. DO NOT EDIT.
// source: WhisperTextProtocol.proto

/*
Package protos is a generated protocol buffer package.

It is generated from these files:
	WhisperTextProtocol.proto
	LocalStorageProtocol.proto
	FingerprintProtocol.proto

It has these top-level messages:
	SignalMessage
	PreKeySignalMessage
	KeyExchangeMessage
	SenderKeyMessage
	SenderKeyDistributionMessage
	DeviceConsistencyCodeMessage
	SessionStructure
	RecordStructure
	PreKeyRecordStructure
	SignedPreKeyRecordStructure
	IdentityKeyPairStructure
	SenderKeyStateStructure
	SenderKeyRecordStructure
	LogicalFingerprint
	CombinedFingerprints
*/
package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SignalMessage struct {
	RatchetKey       []byte  `protobuf:"bytes,1,opt,name=ratchetKey" json:"ratchetKey,omitempty"`
	Counter          *uint32 `protobuf:"varint,2,opt,name=counter" json:"counter,omitempty"`
	PreviousCounter  *uint32 `protobuf:"varint,3,opt,name=previousCounter" json:"previousCounter,omitempty"`
	Ciphertext       []byte  `protobuf:"bytes,4,opt,name=ciphertext" json:"ciphertext,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SignalMessage) Reset()                    { *m = SignalMessage{} }
func (m *SignalMessage) String() string            { return proto.CompactTextString(m) }
func (*SignalMessage) ProtoMessage()               {}
func (*SignalMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SignalMessage) GetRatchetKey() []byte {
	if m != nil {
		return m.RatchetKey
	}
	return nil
}

func (m *SignalMessage) GetCounter() uint32 {
	if m != nil && m.Counter != nil {
		return *m.Counter
	}
	return 0
}

func (m *SignalMessage) GetPreviousCounter() uint32 {
	if m != nil && m.PreviousCounter != nil {
		return *m.PreviousCounter
	}
	return 0
}

func (m *SignalMessage) GetCiphertext() []byte {
	if m != nil {
		return m.Ciphertext
	}
	return nil
}

type PreKeySignalMessage struct {
	RegistrationId   *uint32 `protobuf:"varint,5,opt,name=registrationId" json:"registrationId,omitempty"`
	PreKeyId         *uint32 `protobuf:"varint,1,opt,name=preKeyId" json:"preKeyId,omitempty"`
	SignedPreKeyId   *uint32 `protobuf:"varint,6,opt,name=signedPreKeyId" json:"signedPreKeyId,omitempty"`
	BaseKey          []byte  `protobuf:"bytes,2,opt,name=baseKey" json:"baseKey,omitempty"`
	IdentityKey      []byte  `protobuf:"bytes,3,opt,name=identityKey" json:"identityKey,omitempty"`
	Message          []byte  `protobuf:"bytes,4,opt,name=message" json:"message,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PreKeySignalMessage) Reset()                    { *m = PreKeySignalMessage{} }
func (m *PreKeySignalMessage) String() string            { return proto.CompactTextString(m) }
func (*PreKeySignalMessage) ProtoMessage()               {}
func (*PreKeySignalMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PreKeySignalMessage) GetRegistrationId() uint32 {
	if m != nil && m.RegistrationId != nil {
		return *m.RegistrationId
	}
	return 0
}

func (m *PreKeySignalMessage) GetPreKeyId() uint32 {
	if m != nil && m.PreKeyId != nil {
		return *m.PreKeyId
	}
	return 0
}

func (m *PreKeySignalMessage) GetSignedPreKeyId() uint32 {
	if m != nil && m.SignedPreKeyId != nil {
		return *m.SignedPreKeyId
	}
	return 0
}

func (m *PreKeySignalMessage) GetBaseKey() []byte {
	if m != nil {
		return m.BaseKey
	}
	return nil
}

func (m *PreKeySignalMessage) GetIdentityKey() []byte {
	if m != nil {
		return m.IdentityKey
	}
	return nil
}

func (m *PreKeySignalMessage) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

type KeyExchangeMessage struct {
	Id               *uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	BaseKey          []byte  `protobuf:"bytes,2,opt,name=baseKey" json:"baseKey,omitempty"`
	RatchetKey       []byte  `protobuf:"bytes,3,opt,name=ratchetKey" json:"ratchetKey,omitempty"`
	IdentityKey      []byte  `protobuf:"bytes,4,opt,name=identityKey" json:"identityKey,omitempty"`
	BaseKeySignature []byte  `protobuf:"bytes,5,opt,name=baseKeySignature" json:"baseKeySignature,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *KeyExchangeMessage) Reset()                    { *m = KeyExchangeMessage{} }
func (m *KeyExchangeMessage) String() string            { return proto.CompactTextString(m) }
func (*KeyExchangeMessage) ProtoMessage()               {}
func (*KeyExchangeMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *KeyExchangeMessage) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *KeyExchangeMessage) GetBaseKey() []byte {
	if m != nil {
		return m.BaseKey
	}
	return nil
}

func (m *KeyExchangeMessage) GetRatchetKey() []byte {
	if m != nil {
		return m.RatchetKey
	}
	return nil
}

func (m *KeyExchangeMessage) GetIdentityKey() []byte {
	if m != nil {
		return m.IdentityKey
	}
	return nil
}

func (m *KeyExchangeMessage) GetBaseKeySignature() []byte {
	if m != nil {
		return m.BaseKeySignature
	}
	return nil
}

type SenderKeyMessage struct {
	Id               *uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Iteration        *uint32 `protobuf:"varint,2,opt,name=iteration" json:"iteration,omitempty"`
	Ciphertext       []byte  `protobuf:"bytes,3,opt,name=ciphertext" json:"ciphertext,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SenderKeyMessage) Reset()                    { *m = SenderKeyMessage{} }
func (m *SenderKeyMessage) String() string            { return proto.CompactTextString(m) }
func (*SenderKeyMessage) ProtoMessage()               {}
func (*SenderKeyMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SenderKeyMessage) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *SenderKeyMessage) GetIteration() uint32 {
	if m != nil && m.Iteration != nil {
		return *m.Iteration
	}
	return 0
}

func (m *SenderKeyMessage) GetCiphertext() []byte {
	if m != nil {
		return m.Ciphertext
	}
	return nil
}

type SenderKeyDistributionMessage struct {
	Id               *uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Iteration        *uint32 `protobuf:"varint,2,opt,name=iteration" json:"iteration,omitempty"`
	ChainKey         []byte  `protobuf:"bytes,3,opt,name=chainKey" json:"chainKey,omitempty"`
	SigningKey       []byte  `protobuf:"bytes,4,opt,name=signingKey" json:"signingKey,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SenderKeyDistributionMessage) Reset()                    { *m = SenderKeyDistributionMessage{} }
func (m *SenderKeyDistributionMessage) String() string            { return proto.CompactTextString(m) }
func (*SenderKeyDistributionMessage) ProtoMessage()               {}
func (*SenderKeyDistributionMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *SenderKeyDistributionMessage) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *SenderKeyDistributionMessage) GetIteration() uint32 {
	if m != nil && m.Iteration != nil {
		return *m.Iteration
	}
	return 0
}

func (m *SenderKeyDistributionMessage) GetChainKey() []byte {
	if m != nil {
		return m.ChainKey
	}
	return nil
}

func (m *SenderKeyDistributionMessage) GetSigningKey() []byte {
	if m != nil {
		return m.SigningKey
	}
	return nil
}

type DeviceConsistencyCodeMessage struct {
	Generation       *uint32 `protobuf:"varint,1,opt,name=generation" json:"generation,omitempty"`
	Signature        []byte  `protobuf:"bytes,2,opt,name=signature" json:"signature,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DeviceConsistencyCodeMessage) Reset()                    { *m = DeviceConsistencyCodeMessage{} }
func (m *DeviceConsistencyCodeMessage) String() string            { return proto.CompactTextString(m) }
func (*DeviceConsistencyCodeMessage) ProtoMessage()               {}
func (*DeviceConsistencyCodeMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *DeviceConsistencyCodeMessage) GetGeneration() uint32 {
	if m != nil && m.Generation != nil {
		return *m.Generation
	}
	return 0
}

func (m *DeviceConsistencyCodeMessage) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func init() {
	proto.RegisterType((*SignalMessage)(nil), "libsignal.SignalMessage")
	proto.RegisterType((*PreKeySignalMessage)(nil), "libsignal.PreKeySignalMessage")
	proto.RegisterType((*KeyExchangeMessage)(nil), "libsignal.KeyExchangeMessage")
	proto.RegisterType((*SenderKeyMessage)(nil), "libsignal.SenderKeyMessage")
	proto.RegisterType((*SenderKeyDistributionMessage)(nil), "libsignal.SenderKeyDistributionMessage")
	proto.RegisterType((*DeviceConsistencyCodeMessage)(nil), "libsignal.DeviceConsistencyCodeMessage")
}

func init() { proto.RegisterFile("WhisperTextProtocol.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 448 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0xcb, 0x6e, 0xd3, 0x40,
	0x14, 0x95, 0x93, 0x52, 0xda, 0x4b, 0x52, 0x2a, 0xb3, 0x31, 0x55, 0x84, 0x22, 0x4b, 0xa0, 0x88,
	0x45, 0xfe, 0x80, 0x4d, 0x53, 0x16, 0x55, 0x84, 0x14, 0xb9, 0x48, 0x48, 0x88, 0x05, 0xce, 0xf8,
	0xca, 0xbe, 0x92, 0x3b, 0x63, 0xcd, 0x8c, 0x43, 0xfc, 0x07, 0xec, 0xf9, 0x0d, 0xfe, 0x87, 0xdf,
	0x41, 0x33, 0xe3, 0x57, 0x6c, 0xc1, 0xa2, 0xbb, 0xb9, 0x67, 0x1e, 0xe7, 0xdc, 0x73, 0xe6, 0xc2,
	0xeb, 0x2f, 0x19, 0xa9, 0x02, 0xe5, 0x67, 0x3c, 0xea, 0x9d, 0x14, 0x5a, 0x30, 0x91, 0xaf, 0x0b,
	0xb3, 0xf0, 0x2f, 0x73, 0xda, 0x2b, 0x4a, 0x79, 0x9c, 0x87, 0xbf, 0x3c, 0x98, 0x3f, 0xd8, 0xe5,
	0x27, 0x54, 0x2a, 0x4e, 0xd1, 0x7f, 0x03, 0x20, 0x63, 0xcd, 0x32, 0xd4, 0x5b, 0xac, 0x02, 0x6f,
	0xe9, 0xad, 0x66, 0x51, 0x0f, 0xf1, 0x03, 0x78, 0xce, 0x44, 0xc9, 0x35, 0xca, 0x60, 0xb2, 0xf4,
	0x56, 0xf3, 0xa8, 0x29, 0xfd, 0x15, 0xbc, 0x2c, 0x24, 0x1e, 0x48, 0x94, 0x6a, 0x53, 0x9f, 0x98,
	0xda, 0x13, 0x43, 0xd8, 0x70, 0x30, 0x2a, 0x32, 0x94, 0x1a, 0x8f, 0x3a, 0x38, 0x73, 0x1c, 0x1d,
	0x12, 0xfe, 0xf1, 0xe0, 0xd5, 0x4e, 0xe2, 0x16, 0xab, 0x53, 0x6d, 0xef, 0xe0, 0x4a, 0x62, 0x4a,
	0x4a, 0xcb, 0x58, 0x93, 0xe0, 0xf7, 0x49, 0xf0, 0xcc, 0x12, 0x0c, 0x50, 0xff, 0x06, 0x2e, 0x0a,
	0x7b, 0xfd, 0x3e, 0xb1, 0x1d, 0xcc, 0xa3, 0xb6, 0x36, 0x6f, 0x98, 0xde, 0x31, 0xd9, 0x35, 0x27,
	0xce, 0xdd, 0x1b, 0xa7, 0xa8, 0xe9, 0x73, 0x1f, 0x2b, 0x53, 0xd8, 0x3e, 0x67, 0x51, 0x53, 0xfa,
	0x4b, 0x78, 0x41, 0x09, 0x72, 0x4d, 0xba, 0x32, 0xbb, 0x53, 0xbb, 0xdb, 0x87, 0xcc, 0xdd, 0x47,
	0x27, 0xb9, 0x6e, 0xae, 0x29, 0xc3, 0xdf, 0x1e, 0xf8, 0x5b, 0xac, 0x3e, 0x1e, 0x59, 0x16, 0xf3,
	0x14, 0x9b, 0xc6, 0xae, 0x60, 0x42, 0x8d, 0xd4, 0x09, 0xfd, 0x8f, 0xfc, 0x34, 0x9e, 0xe9, 0x28,
	0x9e, 0x81, 0xb8, 0xb3, 0xb1, 0xb8, 0xf7, 0x70, 0x5d, 0x3f, 0x66, 0xcd, 0xd5, 0xa5, 0x44, 0x6b,
	0xe3, 0x2c, 0x1a, 0xe1, 0xe1, 0x77, 0xb8, 0x7e, 0x40, 0x9e, 0xa0, 0xdc, 0x62, 0xf5, 0x2f, 0xad,
	0x0b, 0xb8, 0x24, 0x8d, 0xce, 0xfb, 0xfa, 0x4b, 0x74, 0xc0, 0x20, 0xea, 0xe9, 0x28, 0xea, 0x9f,
	0x1e, 0x2c, 0x5a, 0x8a, 0x3b, 0x13, 0x22, 0xed, 0x4b, 0x73, 0xf3, 0x69, 0x74, 0x37, 0x70, 0xc1,
	0xb2, 0x98, 0x78, 0x67, 0x4e, 0x5b, 0x1b, 0x29, 0x26, 0x63, 0xe2, 0x69, 0xe7, 0x4c, 0x0f, 0x09,
	0xbf, 0xc1, 0xe2, 0x0e, 0x0f, 0xc4, 0x70, 0x23, 0xb8, 0x22, 0xa5, 0x91, 0xb3, 0x6a, 0x23, 0x12,
	0xec, 0x4d, 0x46, 0x8a, 0xbc, 0xa1, 0x76, 0x8a, 0x7a, 0x88, 0x51, 0xa6, 0x5a, 0x47, 0x5d, 0x6c,
	0x1d, 0x70, 0xfb, 0x01, 0xde, 0x0a, 0x99, 0xae, 0x7f, 0xb8, 0xa9, 0x54, 0x95, 0xd2, 0xf8, 0xa8,
	0xd6, 0xed, 0x24, 0xba, 0xd1, 0x64, 0x22, 0xbf, 0x9d, 0xb9, 0x3f, 0x6f, 0x67, 0x56, 0x7d, 0x3d,
	0xb7, 0xb8, 0xfa, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xe6, 0xbd, 0xad, 0x10, 0xcf, 0x03, 0x00, 0x00,
}
